<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contoso.Application\Contoso.Application.csproj" />
    <ProjectReference Include="..\Contoso.Infrastructure\Contoso.Infrastructure.csproj" />
    <ProjectReference Include="..\Contoso.Catalog\Contoso.Catalog.csproj" />
  </ItemGroup>
</Project>
